### ISSUE TITLE
Einstellungen Passwortschützen

### ISSUE THREAD

**Issue by Tronje-the-Falconer** [Tronje-the-Falconer/Reifeschrank#16]
Auslagern in einen Unterordner

oder

einer .htaccess die im gleichen Ordner liegt wie die zu schützende Datei.
Die .htaccess hat folgenden Inhalt:

    AuthName "Administration"
    AuthType Basic
    AuthUserFile /pfadzur/.htpasswd
    <Files zuschuetzendedatei.php>
        require valid-user
    </Files>

eine .htpasswd in der die Benutzernamen und zugehörigen, verschlüsselten Passwörter stehen (Benutzername:verschlüsseltesPasswort).

    Heinz:69gY8YPjQXeN6
    Klaus:INw2mPEH.owe2

Die Passwörter werden mit crypt oder md5 verschlüssel.
Das ist z.B. unter [http://www.htaccesstools.com/htpasswd-generator/](http://www.htaccesstools.com/htpasswd-generator/) möglich.

Für das noob Image
openssl passwd -1 password

**Comment by GSV-Steinbacher** [comment]
Mein Vorschlag: einfach die .htaccess und die .htpasswd in /www/ legen. Das schützt den gesammten Content. Da weiß ein Angreifer nicht mal, was das für ein Teil ist.

**Comment by Tronje-the-Falconer** [comment]
in neuem Release enthalten
